INSERT INTO INFO VALUES (CURRENT_TIMESTAMP);

-- Types
INSERT INTO TYPE_OPTION VALUES(1, 'Console');
INSERT INTO TYPE_OPTION VALUES(2, 'Book');
INSERT INTO TYPE_OPTION VALUES(3, 'Software');
INSERT INTO TYPE_OPTION VALUES(4, 'Game');
INSERT INTO TYPE_OPTION VALUES(5, 'Computer');
INSERT INTO TYPE_OPTION VALUES(6, 'Peripheral');
INSERT INTO TYPE_OPTION VALUES(7, 'Gadget');
