INSERT INTO INFO VALUES (CURRENT_DATE);

-- Tags
INSERT INTO TAG_OPTION VALUES (1, 'CIB');
INSERT INTO TAG_OPTION VALUES(2, 'PAL');
INSERT INTO TAG_OPTION VALUES(3, 'PlayStation');
INSERT INTO TAG_OPTION VALUES(4, 'Nintendo DS');

-- Types
INSERT INTO TYPE_OPTION VALUES(1, 'Console');
INSERT INTO TYPE_OPTION VALUES(2, 'Book');
INSERT INTO TYPE_OPTION VALUES(3, 'Software');
INSERT INTO TYPE_OPTION VALUES(4, 'Game');
INSERT INTO TYPE_OPTION VALUES(5, 'Computer');
INSERT INTO TYPE_OPTION VALUES(6, 'Periferica');
INSERT INTO TYPE_OPTION VALUES(7, 'Gadget');

INSERT INTO CIUSKY VALUES(1, 'Pokémon HeartGold', 'Pokémon HeartGold Nintendo DS | Completo ITA + Pokéwalker | Raro Originale PAL', 4, 4, 50, 205);
INSERT INTO CIUSKY_TAG VALUES(1, 1);
INSERT INTO CIUSKY_TAG VALUES(1, 2);
INSERT INTO CIUSKY_TAG VALUES(1, 4);

INSERT INTO CIUSKY VALUES(2, 'Final Fantasy Origins', 'Final Fantasy Origins', 4, 5, 6, 100);
INSERT INTO CIUSKY_TAG VALUES(2, 1);
INSERT INTO CIUSKY_TAG VALUES(2, 2);
INSERT INTO CIUSKY_TAG VALUES(2, 3);

