INSERT INTO INFO VALUES (CURRENT_DATE);

INSERT INTO PERSON (NAME, CONTACT_NUMBER, EMAIL, SUPERVISOR) VALUES ('Gino', '3323232', 'gino@test.it', FALSE);
INSERT INTO PERSON (NAME, CONTACT_NUMBER, EMAIL, SUPERVISOR) VALUES ('Matteo Metto', '23123', 'matteometto@test.it', FALSE);
INSERT INTO PERSON (NAME, CONTACT_NUMBER, EMAIL, SUPERVISOR) VALUES ('Baz', '123123', 'bazinga@test.it', FALSE);

