
CREATE TABLE INFO (
   INIT_DATE TIMESTAMP NOT NULL
);

CREATE TABLE TAG_OPTION (
    ID IDENTITY,
    DESCR VARCHAR2(256),
    PRIMARY KEY (ID)
);

CREATE TABLE TYPE_OPTION (
    ID IDENTITY,
    DESCR VARCHAR2(256),
    PRIMARY KEY (ID)
);

CREATE TABLE CIUSKY (
   ID IDENTITY,
   TITLE VARCHAR(256) NOT NULL,
   DESCRIPTION CLOB,
   TYPE_OPTION BIGINT,
   QUALITY INTEGER,
   PAID_PRICE NUMERIC(20, 2),
   MARKET_PRICE NUMERIC(20, 2),
   PRIMARY KEY (ID)
);

CREATE TABLE BOOK (
   ID BIGINT,
   AUTHOR VARCHAR(256),
   FORMATO VARCHAR(256),
   PUBLISHER VARCHAR(256),
   DATA_PUBBLICAZIONE DATE,
   ISBN_13 VARCHAR(13),
   `LANGUAGE` VARCHAR2(2),
   PRIMARY KEY (ID),
   FOREIGN KEY (ID) REFERENCES CIUSKY(ID) ON DELETE CASCADE
);

CREATE TABLE CIUSKY_TAG(
    ID BIGINT,
    TAG_OPTION BIGINT,
    PRIMARY KEY (ID, TAG_OPTION),
    FOREIGN KEY (ID) REFERENCES CIUSKY(ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_OPTION) REFERENCES TAG_OPTION(ID) ON DELETE SET NULL
);
