
CREATE TABLE INFO (
   INIT_DATE TIMESTAMP NOT NULL
);

CREATE TABLE TYPE_OPTION (
    ID IDENTITY,
    DESCR VARCHAR2(256),
    PRIMARY KEY (ID)
);

CREATE TABLE CIUSKY (
   ID IDENTITY,
   TITLE VARCHAR(256) NOT NULL,
   DESCRIPTION CLOB,
   TYPE_OPTION BIGINT NOT NULL,
   QUALITY INTEGER,
   PURCHASE_PLACE VARCHAR2(256),
   PURCHASE_DATE DATE,
   PAID_PRICE NUMERIC(20, 2),
   MARKET_PRICE NUMERIC(20, 2),
   NOTES CLOB,
   PRIMARY KEY (ID)
);

CREATE TABLE BOOK (
   ID BIGINT,
   AUTHOR VARCHAR(256),
   FORMAT VARCHAR(256),
   PUBLISHER VARCHAR(256),
   PUBLISH_DATE DATE,
   ISBN_13 VARCHAR(13),
   `LANGUAGE` VARCHAR2(2),
   PRIMARY KEY (ID),
   FOREIGN KEY (ID) REFERENCES CIUSKY(ID) ON DELETE CASCADE
);

CREATE TABLE CIUSKY_TAG(
    ID BIGINT,
    `KEY` VARCHAR2(256) NOT NULL,
    `VALUE` VARCHAR2(256) NOT NULL,
    PRIMARY KEY (ID, `KEY`, `VALUE`),
    FOREIGN KEY (ID) REFERENCES CIUSKY(ID) ON DELETE CASCADE
);


CREATE TABLE CIUSKY_IMG(
    ID BIGINT,
    UUID VARCHAR2(36),
    NAME VARCHAR2(256),
    PRIMARY KEY (ID, UUID),
    FOREIGN KEY (ID) REFERENCES CIUSKY(ID) ON DELETE CASCADE
);


